### ISSUE TITLE
MacOSX: problem report of nbody_3d.py

### ISSUE THREAD

**Issue by iamyoukou** [IteratorAdvance/taichi#23]
On MacOSX(10.11.6), some errors will happen when execute `nbody_3d.py`.  
I fixed them in a not clever way, but it works for me.  

1. 
 ```
Traceback (most recent call last):
  File "nbody_3d.py", line 1, in <module>
    from taichi.dynamics.nbody import NBody
  File "/Users/YJ-work/Desktop/taichi_root/taichi/python/taichi/dynamics/nbody.py", line 6, in <module>
    from taichi.tools.video import VideoManager
  File "/Users/YJ-work/Desktop/taichi_root/taichi/python/taichi/tools/video.py", line 1, in <module>
    from taichi import ndarray_to_array2d
ImportError: cannot import name ndarray_to_array2d
```
I replaced `from taichi import ndarray_to_array2d` with `from taichi.misc.util import ndarray_to_array2d` in `taichi.tools.video`.

2.
```
[Errno 2] No such file or directory: '/Users/YJ-work/Desktop/taichi_root//taichi_outputs///task-2017-01-10-21-51-00-r07015'
Simulation time: 0.0
nbody.cpp[201]: node_end = 297117
Time: 0.0983819961548
Segmentation fault: 11
```
I replaced `self.directory = taichi.get_output_path(get_unique_task_id())` with a full path `self.directory = '/Users/YJ-work/Desktop/taichi_root/taichi/output/'` in `taichi.dynamics.nbody`

3.
```
Traceback (most recent call last):
  File "nbody_3d.py", line 6, in <module>
    nbody.step(0.01)
  File "/Users/YJ-work/Desktop/taichi_root/taichi/python/taichi/dynamics/nbody.py", line 49, in step
    img = LDRDisplay(exposure=1, adaptive_exposure=False).process(img)
NameError: global name 'LDRDisplay' is not defined
```
I added `from taichi.visual.post_process import LDRDisplay` in `taichi.dynamics.nbody`.

4.
```
Traceback (most recent call last):
  File "nbody_3d.py", line 6, in <module>
    nbody.step(0.01)
  File "/Users/YJ-work/Desktop/taichi_root/taichi/python/taichi/dynamics/nbody.py", line 53, in step
    self.video_manager.write_frame(img)
  File "/Users/YJ-work/Desktop/taichi_root/taichi/python/taichi/tools/video.py", line 18, in write_frame
    ndarray_to_array2d(img).write(self.directory + '/%05d.png' % self.frame_counter)
AttributeError: 'NoneType' object has no attribute 'write'
```
I commented out `self.video_manager.write_frame(img)` in `taichi.dynamics.nbody`.

Maybe there is a clever way to fix this problem.

BTW, I got this output (one of those frames)
![image](https://cloud.githubusercontent.com/assets/7427716/21807319/85915a16-d781-11e6-8871-6f10d2c5f17c.png)
Is it correct?

**Comment by IteratorAdvance** [comment]
Thanks for letting me know. I think they are fixed in later commits and to fix 2 you may want to execete 
```
mkdir $TAICHI_ROOT_DIR/taichi_outputs
```

Please just pull and see if everything goes well.

**Comment by iamyoukou** [comment]
I pull the latest one, and it works well. Thanks : )

**Comment by IteratorAdvance** [comment]
Cool. Thanks :-)
